### DISCUSSION TITLE
Deploying Parcel build to GitLab Pages

### DISCUSSION THREAD

**Discussion by hchauvat** [parcel-bundler/parcel#5095] [General] [answered]
Hi, 

I'm kinda new to Parcel and I'm facing an issue with paths in HTML tag (css, img).

**index.html:**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My First Parcel App</title>
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```
**css/style.css**
```css
h1 {
  font-family: "Courier New", Courier, monospace;
  color: palegreen;
}
```
**Then building:**
```shell
parcel build index.html
```
**Output:**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My First Parcel App</title>
    <link rel="stylesheet" href="/style.9de6fc69.css" /> <!-- <- absolute path here -->
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```
**Then deploying to GitLab Pages:**
```yaml
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
```
**My issue:** 
If I try to open the dist/index.html from my filesystem or on GitLab Pages, I end up with the following issue: 
![image](https://user-images.githubusercontent.com/59441901/92090282-898db480-edcf-11ea-9035-ea2086198afd.png)

Is there a specific way to build in this case? 

Any help would be greatly appreciated!
