### DISCUSSION TITLE
How do I stop parcel adding suffixes to classes (LESS)

### DISCUSSION THREAD

**Discussion by radiosilence** [parcel-bundler/parcel#5201] [General]
I'm including `antd` like so:

```less
@import '~antd/dist/antd.compact.less';

@text-color: #a0a0a0;
@heading-color: @text-color;
@body-background: #363636;
@component-background: #545454;
@input-bg: #dddddd;
@input-color: #363636;
@btn-default-bg: #999999;
@border-color-base: @component-background;
@menu-item-active-bg: @body-background;
@menu-dark-item-active-bg: @component-background;
@btn-default-color: @body-background;
@layout-body-background: @body-background;
@layout-sider-background: @body-background;
@layout-header-background: @body-background;
@text-color-secondary: @text-color;
@layout-header-color: @text-color;
@collapse-header-bg: @body-background;
```

But the compiled CSS file that parcel generates looks like this:

```css
._ant-image-preview_c82c8 {
  pointer-events: none;
}
._ant-modal_c82c8._zoom-enter_c82c8,
._ant-modal_c82c8._zoom-appear_c82c8,
._ant-image-preview_c82c8._zoom-enter_c82c8,
._ant-image-preview_c82c8._zoom-appear_c82c8 {
  transform: none;
  opacity: 0;
  animation-duration: 0.3s;
  user-select: none;
}
._ant-modal-mask_c82c8,
._ant-image-preview-mask_c82c8 {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1000;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.45);
  filter: alpha(opacity=50);
}
```

As you can see, `_c82c8` is added to every class, along with a leading `_`. Why does it do this? How can I prevent this? It means that the ant design components do not work because they do not have this suffix on their classes.
