### DISCUSSION TITLE
Make Parcel 2 use different postcss configuration for different targets

### DISCUSSION THREAD

**Discussion by Andrew-Dyachenko** [parcel-bundler/parcel#5730] [Q&A]
# 🎯 Target

My main goal is to get [Parcel 2](https://v2.parceljs.org/) to use a different [postcss](https://v2.parceljs.org/languages/postcss/) configuration for different [targets](https://v2.parceljs.org/configuration/package-json/#targets), to split CSS code into two parts, for **[modern]** browsers and **[legacy]** browsers.

Unfortunately, I didn't find the information I needed in the [Parcel 2](https://v2.parceljs.org/) documentation.
I found a reference to a similar problem earlier in the discussion of the [Parcel 1](https://parceljs.org) here #41, but this information is not enough to me too, I do not understand how can I apply this in practices in my case.

### package.json
```json
{
    "name": "project-name",
    "engines": {
        "node": "14"
    },
    "isLibrary": false,
    "targets": {
        "legacy": {
            "engines": {
                "browsers": [
                    ">= 0.25%",
                    "maintained node versions"
                ]
            },
            "isLibrary": false,
            "minify": false
        },
        "modern": {
            "engines": {
                "browsers": [
                    "defaults",
                    "not IE 11",
                    "maintained node versions"
                ]
            },
            "isLibrary": false,
            "minify": false
        }
    },
    "scripts": {
        "serve": "parcel serve templates/layouts/index.pug",
        "build": "parcel build templates/layouts/index.pug --dist-dir ./build"
    }
}
```

### .postcssrc
```json
{
    "modules": false,
    "plugins": {
        "autoprefixer": {
            "grid": "autoplace",
            "flexbox": true,
            "cascade": false,
            "remove": false
        }
    }
}
```

## 🤔 Expected Behavior

- **[modern]** browsers such as latest _Google Chrome_, _Firefox_ should get a more compact CSS, without unnecessary for modern browsers CSS code.
- **[legacy]** browsers such as _IE11_ should get a more complete CSS, with additional prefixes such as `display: -ms-grid;` respectively

#### Expected to see
![Expected parcel 2 bundler css files display after postcss with autoprefixer transforms for multiple targets build, modern and legacy browsers](https://user-images.githubusercontent.com/10127643/106137191-6c40f480-617b-11eb-9302-8d817207f064.png)

## 😯 Current Behavior

After the build command

```bash
yarn build
```

the output is: two created directories `modern/` and `legacy/`

```bash
tree
```

```bash
MacBook-Pro-Andrey:build andrew$ tree
.
├── legacy
│   ├── index.html
│   └── styles.a621ca41.css
└── modern
    ├── index.html
    └── styles.13dc2168.css

2 directories, 4 files
MacBook-Pro-Andrey:build andrew$
```

#### `legacy/styles.a621ca41.css`
```css
.navbar__container {
    display: -ms-grid;
    display: grid;
    flex-grow: 1;
    grid-auto-flow: column;
    grid-template-areas:
        ". . .             . .              "
        ". . navbar__brand . navbar__toggler"
        ". . .             . .              ";
    -ms-grid-columns: 32px 16px 1fr 16px 32px;
    grid-template-columns: 32px 16px 1fr 16px 32px;
    -ms-grid-rows: 16px 1fr 16px;
    grid-template-rows: 16px 1fr 16px;
}
```

#### `modern/styles.13dc2168.css`
```css
.navbar__container {
  display: -ms-grid;
  display: grid;
  flex-grow: 1;
  grid-auto-flow: column;
  grid-template-areas:
	  ". . .             . .              "
	  ". . navbar__brand . navbar__toggler"
	  ". . .             . .              ";
  -ms-grid-columns: 32px 16px 1fr 16px 32px;
  grid-template-columns: 32px 16px 1fr 16px 32px;
  -ms-grid-rows: 16px 1fr 16px;
  grid-template-rows: 16px 1fr 16px;
}
```

😐 The output in the build CSS files above contains equivalent content internally - I checked it fully with a diff tool ...
This is not surprising because there is only one `.postcssrc` config file at the project root.

The question is how to divide `.postcssrc` autoprefix config into two different targets?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.1
| Node             |v14.15.3
| npm/Yarn         |6.14.9/1.19.0
| Operating System |macOS Catalina 10.15.7
