### DISCUSSION TITLE
How to tell parcel not to resolve `url(../relative/path.png)` in SCSS?

### DISCUSSION THREAD

**Discussion by balthild** [parcel-bundler/parcel#6157] [Q&A]
For example, I want the `background-image` property in the following SCSS be compiled as-is, and do not resolve the relative path inside `url()`. Currently Parcel gives me an error message that the file is not found (of course). Also not that I just want to turn off path resolving for some specific paths, not globally. How can I do that? 

```scss
.has-bg {
    background-image: url(../relative/path.png);
}
```
