### DISCUSSION TITLE
CSS Custom properties not transpiled by default but warning if PostCSS is added

### DISCUSSION THREAD

**Discussion by axelgar** [parcel-bundler/parcel#8117] [Q&A] [answered]
Hello community 🙂

I wanted to add this as a discussion before opening an issue just in case I'm missing something.

By default, Parcel transpiles the CSS for older browsers if the browserslist is present and it will add the required prexies ([as the documentation says](https://parceljs.org/languages/css/#browser-targets)). This all works perfectly. But one thing that it doesn't do for me is to fill in the custom properties I implemented in my CSS. Here is an example:

**CSS before transpailing:** 
``` css
:root {
  --green-main: #00b67d;
}

.Pager.NumberedPager {
  border-radius: 6px;
}

.Pager.NumberedPager > * {
  border: 1px solid var(--green-main);
}
```

**CSS after transpiling (by default):**
``` css
:root {
  --green-main: #00b67d;
}

.Pager.NumberedPager {
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
}

.Pager.NumberedPager > * {
  border: 1px solid var(--green-main);
}

```

----
Same example but now adding the `.postcssrc` file with the following configuration ([here is the documentation](https://parceljs.org/languages/css/#postcss)):
``` json
{
  "plugins": {
    "postcss-preset-env": true
  }
}
```

**CSS after transpiling (with PostCSS):**
``` css
:root {
  --green-main: #00b67d;
}
.Pager.NumberedPager {
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
}

.Pager.NumberedPager > * {
  border: 1px solid #00b67d; /* 1 */
  border: 1px solid var(--green-main);
}

```

This transpiles the custom properties as seen in line `/* 1 */` but with an extra warning in the console:

> ⚠️ @parcel/transformer-postcss: Parcel includes CSS transpilation and vendor prefixing by default. PostCSS config
.postcssrc contains only redundant plugins. Deleting it may significantly improve build performance.

I feel this might be misleading since someone can think everything is transpiling in the same way but is not right? 

What do you think? Let me know if it was me that I was missing some extra step.
Thank you so much!
