### ISSUE TITLE
using of .sassrc.js messes sass output with multiple entry points

### ISSUE THREAD

**Issue by safareli** [parcel-bundler/parcel#1280]
This a 🐛 bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

index.html
```html
 index.html
<html>
<head>
  <link href='A.scss' rel='stylesheet' />
  <link href='B.scss' rel='stylesheet' />
</head>
<body>
  hi
</body>
</html>
```

package.json
```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.7.1"
  }
}
```

 .sassrc.js 
```js
module.exports = {};
```

A.scss
```scss
.A { color: black }
```

B.scss
```scss
.B { color: blue }
```

### 🤔 Expected Behavior

dist/A.css
```css
.A {
  color: black }
```

dist/B.css
```css
.B {
  color: blue }
```
### 😯 Current Behavior

dist/A.css
```css
.A {
  color: black; }
```

dist/B.css
```css
.A {
  color: black; }

.B {
  color: blue; }
```

here is somewhat full dump of the test case https://gist.github.com/safareli/8200eccaa6f3a90cf9888a1d2a5bee1b

Issue is that `dist/B.css` contains contents of `A.scss`. If you remove `.sassrc.js` or use `.sassrc` with `{}` as contents then the issue is not present. Why do I need `.sassrc.js` instead of `.sassrc`? as it's the way to depend on staff from node_modules or bower_components etc.. see https://github.com/parcel-bundler/parcel/issues/39#issuecomment-353722786
