### ISSUE TITLE
Using of .sassrc.js messes scss/sass watch

### ISSUE THREAD

**Issue by safareli** [parcel-bundler/parcel#1291]
This a 🐛 bug report.

### 🎛 Setup

.sassrc.js
```js
module.exports = {};
```
(if instead i have `.sassrc` with `{}` I don't have this issue. Why do I need .sassrc.js instead of .sassrc? as it's the way to depend on staff from node_modules or bower_components etc.. see https://github.com/parcel-bundler/parcel/issues/39#issuecomment-353722786)

index.html
```
<html>
  <body>
    <script type="text/javascript" src="./index.js"></script>
  </body>
</html>
```

index.js
```js
require("./index.scss");
```
(same issue with using just a link tag in html)

index.scss
```scss
.red { color: red; }
```

run `parcel watch index.html` and check `dist/*.css` it would be: (as expected)
```css
.red {
  color: red; }
```

edit index.scss to and save file:
```scss
.red2 { color: red; }
```

now `dist/*.css` file would be **appended** with new results instead of been overwritten:
```css
.red {
  color: red; }
.red2 {
  color: red; }
```

you can edit and save or just safe without editing, result of compiling current index.scss file is **appended** to `dist/*.css` 

### 💁 Possible Solution
I guess somewhere results of compilation is appended to css file instead of overriding.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1 |
| Node             | 6.11.4 |
| npm         | 5.4.2 |
| node-sass | 4.8.3 |

also see #1280
