### ISSUE TITLE
How to resolve `url()`s in stylesheets?

### ISSUE THREAD

**Issue by dspacejs** [parcel-bundler/parcel#1351]
# ❔ Question

How can you resolve assets declared in `url()` statements inside stylesheets?

## 🔦 Context

The `@import`s in my Sass files works fine, but resolving `url()`s doesn't. I've been messing around with this and can't figure out how to get it work.

My directory structure is as follows:

```
assets
├── fonts
├── html
├── img
├── js
└── scss
```

Here's an example of the code I've tried:

```css
@font-face {
  font-family: 'icomoon';
  src:  url('/assets/fonts/icomoon.eot?5yevc3');
  src:  url('/assets/fonts/icomoon.eot?5yevc3#iefix') format('embedded-opentype'),
    url('/assets/fonts/icomoon.ttf?5yevc3') format('truetype'),
    url('/assets/fonts/icomoon.woff?5yevc3') format('woff'),
    url('/assets/fonts/icomoon.svg?5yevc3#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

And here's my `.sassrc.js`:

```
const path = require('path');
const CWD = process.cwd();

module.exports = {
  includePaths: [
    path.resolve(CWD, 'node_modules'),
    path.resolve(CWD, 'assets/scss'),
  ],
};
```

I've also tried adding `path.resolve(CWD, 'assets/fonts'),` to `includePaths`, then importing fonts like `./icomoon.eot`, but that didn't work either.

Another thing I tried is configuring `postcss-assets` to resolve `url()`s correctly, but it seems like this is an issue with the Parcel resolver itself so it didn't fix it.

## 💻 Code Sample

Here's the error I'm getting:

```
🚨  /home/daniel/Dev/projects/vibite/assets/js/components/layout/__styles__/App.scss: Cannot resolve dependency './icomoon.eot' at '/hom🚨  /home/daniel/Dev/projects/vibite/assets/js/components/layout/__styles__/App.scss: Cannot resolve dependency './../../../../../../../../../../assets/fonts/icomoon.eot' at '/assets/fonts/icomoon.eot'
    at Resolver.resolve (/home/daniel/Dev/projects/vibite/node_modules/parcel-bundler/src/Resolver.js:70:17)
    at <anonymous>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.10.0
| npm         | 6.0.0
| Operating System | Ubuntu 18.04

**Comment by DeMoorJasper** [comment]
Absolute paths are probably not supported in sass yet

**Comment by dspacejs** [comment]
@DeMoorJasper thanks, that's fine though, I just need a way to import these assets with `url()`. Is there any way to do it?

**Comment by SteffenL** [comment]
Can you please try `url()` without quotes (and use relative paths)?

**Comment by dspacejs** [comment]
@SteffenL Sure, just tried a bunch of relative paths:

* `./fonts/`
* `../fonts/`
* `./assets/fonts/

None of those worked. It's not throwing any errors but the fonts aren't loading. 

If you mean relative to the file it's imported in, that's not feasible. Many of my React components have stylesheets (and they're all in different folders), so then I'd have to navigate backwards using `../../../../` for any asset I use in `url()`

**Comment by DeMoorJasper** [comment]
@dspacejs it should be relative to the css file, haven’t seen this issue before and the tests pass so not sure why this is breaking

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dspacejs** [comment]
@DeMoorJasper right, well I tried `../fonts/` which is the correct path if it's meant to be relative to the stylesheet. The assets aren't being loaded but there's no error

**Comment by dspacejs** [comment]
Looks like relative paths are being used in the build, not sure if that's normal. This CSS is showing in the inspector: `background-image: url(../../img/home-page-bg.jpg);`

**Comment by DeMoorJasper** [comment]
The test file is written like this, perhaps you could try `url("../../img/home-page-bg.jpg")`

The test example that works perfectly:
```CSS
@font-face {
  font-family: "Test";
  src: url("./fonts/test.woff2") format("woff2");
}
```

**Comment by dspacejs** [comment]
@DeMoorJasper awesome, that works, thanks :+1: I'll have to reorganise my stylesheets a bit so that relative paths aren't a mess, but it'll work. Cheers

**Comment by fourcolors** [comment]
I'd love absolute paths to be something by default with postcss

**Comment by jussikinnula** [comment]
I created an example stating the issue: https://github.com/jussikinnula/sass-url-issue-with-imports

Basically we would need similar as `resolve-url-loader` either to be implemented in node-sass or as a postcss plugin. The `resolve-url-loader` does resolve the url()'s by looking the files defined in source map. You can see the produced source maps for example by doing a `node-sass` or `ruby-sass` build.

**Comment by tomasdev** [comment]
@DeMoorJasper the tests only resolve for 1 import, not an import inside an import, i.e:
Structure:
```
├─ src/
│  ├─ js
│  └─ scss/
│     ├─ framework/
│     │  ├─ fonts/
│     │  └─ file.scss
│     └─ index.scss
└─ index.html
```

if `index.scss` does `@import 'framework/file'` and `file.scss` does:
```
@font-face {
  font-family: "custom";
  src:
    url("./fonts/custom.woff") format("woff");
}
```

It tries to look it up in `/src/scss/fonts` instead of `/src/scss/framework/fonts` (since the `./` corresponds to where the file is, not where the file was imported from)
```

**Comment by ZiFFeL1992** [comment]
@tomasdev is right, I created a repo which reproduces the issue:
https://github.com/ZiFFeL1992/url-import-issue

**Comment by ZiFFeL1992** [comment]
Should I open a new issue @DeMoorJasper ?

**Comment by shanebo** [comment]
@DeMoorJasper I'm experiencing the same bug as @ZiFFeL1992

**Comment by mischnic** [comment]
Sass doesn't seem to handle these import relative urls and I couldn't find an option for that either (importers are ignored by `dart-sass`: https://github.com/sass/libsass/issues/2483). Sass compiles the example by @ZiFFeL1992 to 
```css
.foo {
  background-image: url("./foo.png");
}

.foo {
  background-image: url("./bar.png");
}
```
The first statement is imported  from a subfolder `others/second_level.scss` but the relative url `./foo.png` is now wrong after the SASS concatenation, it should be `./others/foo.png`.
Why isn't this a more popular issue with Sass itself?
