### ISSUE TITLE
CSS url() asset from node_modules does not find correct directory

### ISSUE THREAD

**Issue by ryan-plated** [parcel-bundler/parcel#1813]
# 🐛 bug report

css url() assets from node_modules are not looked up in the correct directory.

## 🎛 Configuration (.babelrc, package.json, cli command)

index.css
```css
@font-face {
  font-family: "font-awesome";
  src: url("~font-awesome/fonts/fontawesome-webfot.eot") format("embedded-opentype");
}
```
package.json
```js
{
  "dependencies": {
    "font-awesome": "^4.7.0"
  },
}

```

## 🤔 Expected Behavior

I expect the asset to be found correctly in the font-awesome package

## 😯 Current Behavior

Fails to load any assets from node_modules

```
🚨  /Users/ryanong/code/supernova/index.css:3:3: Cannot resolve dependency '/Users/ryanong/code/supernova/font-awesome/fonts/fontawesome-webfot.eot' at '/Users/ryanong/code/supernova/font-awesome/fonts/fontawesome-webfot.eot'
  1 | @font-face {
  2 |   font-family: "font-awesome";
> 3 |   src: url("~font-awesome/fonts/fontawesome-webfot.eot") format("embedded-opentype");
    |   ^
  4 | }
  5 |
```

## 💁 Possible Solution

Looks like addURLDependency in Asset.js only does look up from root directory and doesn't look up from node_modules.

## 🔦 Context

We are trying to create an in house pattern library with fonts and images and we can't use them.
