### ISSUE TITLE
when build the order of properties in css block is change and cause ui problems

### ISSUE THREAD

**Issue by natqe** [parcel-bundler/parcel#1985]
# 🐛 bug report
when build project via parcel build, the components of scss transform in the wrong way, and the order of the properties is change, and is metter in css, so the project is not showing correctly.

## 🎛 Configuration (.babelrc, package.json, cli command)
```json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "./app/index.htm",
  "scripts": {
    "start": "set NODE_ENV=development&node bundler",
    "https": "parcel app/index.htm --no-cache --https -p 506",
    "watch": "set NODE_ENV=development&node bundler",
    "build": "set NODE_ENV=production&node bundler"
  },
  "repository": {
    "type": "git",
    "url": "***"
  },
  "author": "natan farkash",
  "license": "ISC",
  "homepage": "***",
  "dependencies": {
    "angular": "^1.7.3",
    "angular-animate": "^1.7.3",
    "angular-aria": "^1.7.3",
    "angular-material": "^1.1.10",
    "angular-messages": "^1.7.3",
    "angular-route": "^1.7.3",
    "angular-sanitize": "^1.7.3",
    "element-closest": "^2.0.2",
    "lodash": "^4.17.10",
    "moment": "^2.22.2"
  },
  "devDependencies": {
    "@types/angular": "^1.6.50",
    "@types/angular-material": "^1.1.59",
    "@types/angular-route": "^1.7.0",
    "@types/lodash": "^4.14.116",
    "@types/node": "^10.9.4",
    "@types/parcel-env": "0.0.0",
    "autoprefixer": "^9.1.5",
    "node-sass": "^4.9.3",
    "parcel-bundler": "^1.9.7",
    "postcss-modules": "^1.3.2",
    "typescript": "^3.0.3"
  }
}
```
bundler.js : 
```js
const
  { existsSync, readdirSync, unlinkSync } = require('fs'),
  { join } = require('path'),
  production = process.env.NODE_ENV === 'production',
  outDir = join(__dirname, '../views/public')

if (production && existsSync(outDir)) readdirSync(outDir).forEach(file => unlinkSync(join(outDir, file)))

new (require('parcel-bundler'))('app/index.htm', { production, outDir, cache: false })[!production ? 'serve' : 'bundle'](1126)
```
```json
.postcssrc : 
{
  "plugins": {
    "autoprefixer": {
      "browsers": "last 2 versions, > 1%"
    }
  }
}
```
## 🤔 Expected Behavior

To be transform with the  order i declare them

## 😯 Current Behavior

css transforming in other order

## 💁 Possible Solution

change logic or settings

## 🔦 Context

the elements not showing right in the page, and i check them via inspect element and for sure this is the problem.

## 💻 Code Sample
The first code transform to the second:
```scss
:root{
>body{
md-select-menu[multiple] md-option.md-checkbox-enabled[selected] .md-icon:after{
      box-sizing: border-box;
      transform: rotate(45deg);
      position: absolute;
      left: 4.66667px;
      top: 0.22222px;
      display: table;
      width: 6.66667px;
      height: 13.33333px;
      border-width: 2px;
      border-style: solid;
      border-top: 0;
      border-left: 0;
      content: '';
    }
}
}
:root>body md-select-menu[multiple] md-option.md-checkbox-enabled[selected] .md-icon:after {
    -webkit-box-sizing: border-box;
    -webkit-transform: rotate(45deg);
    border-left: 0;
    border-style: solid;
    border-top: 0;
    border-width: 2px;
    box-sizing: border-box;
    content: "";
    display: table;
    height: 13.33333px;
    left: 4.66667px;
    position: absolute;
    top: .22222px;
    transform: rotate(45deg);
    width: 6.66667px;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.X.X
| npm/Yarn         | 6.X.X
| Operating System | windows 10
