### ISSUE TITLE
Die after file is not found in css

### ISSUE THREAD

**Issue by cevek** [parcel-bundler/parcel#2168]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`foo.css`
```css
div {
    background: url(utils/dficon.svg); // some non existing file
} 
```

```
parcel foo.css
```

## 🤔 Expected Behavior
Expected error and wait new changes in code

## 😯 Current Behavior
```
⠸ Building dficon.svg...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '.../dficon.svg'
```
and die

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 10 
| npm/Yarn         | 8
| Operating System | macos
