### ISSUE TITLE
How to import and bundle Typeface Fonts?

### ISSUE THREAD

**Issue by posidron** [parcel-bundler/parcel#2251]
# ❔ Question

Is it *somehow* possible to load the 'typeface-*' fonts with the 'import' statement as it's advertised in their docs? I am aware that their docs also say it's suitable for Webpack environment but I would like to know why exactly this won't work with Parcel (or does it?) AND how I should do it instead.

Is the only alternative to place a copy of the font in a local sub-folder and `@import` the font with a custom `.css` file?

## 🔦 Context

I am running the Material UI inside Electron and packing it with Parcel, it all works out, except this.

## 💻 Code Sample

```
import 'typeface-roboto'
```

Results in:

Error:
```Uncaught SyntaxError: Invalid or unexpected token```

## 🌍 Your Environment

**parcel-bundler.js**
```
const options = {
  outDir: './dist/renderer/development',
  outFile: 'index.html',
  //  publicUrl: './',
  watch: true,
  cache: true,
  cacheDir: '.cache',
  contentHash: false,
  minify: false,
  scopeHoist: false,
  target: 'electron',
  https: false,
  logLevel: 3,
  hmrPort: 0,
  sourceMaps: true,
  hmrHostname: '',
  detailedReport: false
}
[...]
```

**.babelrc**
```
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-flow",
    [
      "@babel/preset-env",
      {
        "targets": {
          "electron": "3.0"
        }
      }
    ]
  ],
  "plugins": [["@babel/plugin-proposal-class-properties", { "loose": false }]]
}
```
**package.json**
```
"devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "electron": "^3.0.7",
    "electron-builder": "^20.31.2",
    "electron-devtools-installer": "^2.2.4",
    "parcel-bundler": "^1.10.3"
},
"dependencies": {
    "@material-ui/core": "^3.3.2",
    "@material-ui/icons": "^3.0.1",
    "express": "^4.16.4",
    "prop-types": "^15.6.2",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-router-dom": "^4.3.1"
    "typeface-roboto": "^0.0.54"
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v11.1.0
| Yarn         | 1.12.1
| Operating System | MacOS 10.14.2

**Comment by posidron** [comment]
Okay, I solved it by creating a separate `font.css` which uses the `@font-face` rules for importing the local installed `.woff` files and imported that instead.

**Comment by athenawisdoms** [comment]
@posidron Can you please share your solution? Thanks!

**Comment by pr1ntr** [comment]
I think he meant this:
index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://use.typekit.net/pfl3ivt.css">
    <link rel="stylesheet" href="fonts.css">

    <title>Quiz</title>
</head>

<body>
    <div id="app"></div>
    <script src="index.js"></script>
</body>

</html>

```

fonts.css
```css
@font-face {
    font-family: 'tt-norms-medium';
    src: url('./fonts/TTNormsPro-Medium.woff2') format('woff2'),
    url('./fonts/TTNormsPro-Medium.woff') format('woff');
    font-style: normal;
    font-weight: 400;
}

@font-face {
    font-family: 'tt-norms-bold';
    src: url('./fonts/TTNormsPro-Bold.woff2') format('woff2'),
    url('./fonts/TTNormsPro-Bold.woff') format('woff');
    font-style: normal;
    font-weight: 400;
}

@font-face {
    font-family: 'begum-bold';
    src: url('./fonts/Begum-Bold.woff2') format('woff2'),
    url('./fonts/Begum-Bold.woff') format('woff');
    font-style: normal;
    font-weight: 400;
}

```
