### ISSUE TITLE
Support node module imports in `addUrlDependency`

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#2438]
# 🙋 feature request

addUrlDependency, currently does not support node modules properly afaik.

I can implement this myself, just wondering what the syntax should be for this kind of import.

Example of where this would be usefull
```css
.something {
   background-image: url('node_module/icon.svg');
}
```

## 🤔 Expected Behavior

addUrlDependency should be able to import node_modules

## 😯 Current Behavior

addUrlDependency can't import node_modules

## 💁 Possible Solution

Do something similar to how css imports work
`~node_module` => node_module
`~/path/file` => root path

## 🔦 Context

Trying to import an icon from an icon package in a monorepo.

## 💻 Examples

```scss
.searchbar {
  background: transparent;
  border: none;
  padding: 10px 20px 10px 50px;
  border-radius: 25px;
  color: $black;
  width: 100%;
  font-size: $font-size-14;

  /* This does not work atm */
  background-image: url("~@zf/icons/icons/search-icon.svg");
  background-repeat: no-repeat;
  background-size: 20px;
  background-position: 15px center;
}
```
