### ISSUE TITLE
postcss-custom-properties not working as expected with multiple css-themes

### ISSUE THREAD

**Issue by DeCryptinWeb** [parcel-bundler/parcel#2454]
# 🐛 bug report

Hi

Unfortunately the postcss-custom-properties plugin seems not to work as expected in combination with parceljs.

## 🎛 Setup

package.json
```js
{
    "scripts": {
        "dev-css": "parcel --no-hmr ./src/css/bundle*.pcss",
    }
}
```

.postcssrc.json

```json
{
  "modules": false,
  "plugins": {
    "autoprefixer": true,
    "postcss-custom-properties": {},
    "postcss-nested": {},
    "postcss-import": {}
  }
}
```

/src/css/theme-a.pcss

```css
:root {
    --color: red;
}
```

/src/css/theme-b.pcss

```css
:root {
    --color: green;
}
```

/src/css/componet.pcss

```css
.component {
    background: var(--color);

    .title {
        color: var(--color);
    }
}
```

/src/css/bundle-a.pcss

```css
@import './theme-a.pcss';
@import './component.pcss';

p {
    color: var(--color);
}
```

/src/css/bundle-b.pcss

```css
@import './theme-b.pcss';
@import './component.pcss';

p {
    color: var(--color);
}
```

## 🤔 Expected Behavior

/dist/css/bundle-a.css

```css
:root {
    --color: red;
}

.component {
    background: red;
    background: var(--color);
}

.component .title {
    color: red;
    color: var(--color);
}

p {
    color: red;
    color: var(--color);
}
```

/dist/css/bundle-b.css

```css
:root {
    --color: green;
}

.component {
    background: green;
    background: var(--color);
}

.component .title {
    color: green;
    color: var(--color);
}

p {
    color: green;
    color: var(--color);
}
```

I would expect that each CSS property using the `--color` custom-property gets duplicated and contains the value of `--color`. 

## 😯 Current Behavior

/dist/css/bundle-a.css

```css
:root {
    --color: red;
}

.component {
    background: green;
    background: var(--color);
}

.component .title {
    color: green;
    color: var(--color);
}
    
p {
    color: green;
    color: var(--color);
}
```

/dist/css/bundle-b.css

```css
:root {
    --color: green;
}

.component {
    background: green;
    background: var(--color);
}

.component .title {
    color: green;
    color: var(--color);
}

p {
    color: green;
    color: var(--color);
}
```

Unfortunately the duplicated properties inside bundle-a.css do not contain the correct value. Their value should be red instead of green.

## 💻 Code Sample

repository: https://github.com/DeCryptinWeb/parceljs

After cloning the repo and installing node modules just run `yarn dev-css` or `npm run dev-css`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.13.0
| Yarn             | 1.12.3
| Operating System | Windows 10

Thx in advance!
