### ISSUE TITLE
CSS Modules not compatible using composes imports with SASS

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#2501]
# 🐛 bug report

When using css modules with `composes` from another scss file, the imported file is not transpiled using sass. Everything is working as expected when using `composes` inside the same file.

## 🎛 Configuration (.babelrc, package.json, cli command)

``` scss
// inline.scss
$primary-color: green;

.test {
    height: 100px;
    width: 100px;
    background: $primary-color;
}

// composes.scss
.main {
    composes: test from './inline.scss';
}
```

``` js
// example.js
import * as composes from './composes.scss';

window.onload = () => document.body.innerHTML = `
    <div class="${composes.main}"></div>
`;
```
``` json
// .postcssrc
{
  "modules": true
}
```

``` json
// .sassrc
{
  "includePaths": [
    "node_modules"
  ]
}
```

``` bash
parcel build example.js
```

Please see https://github.com/garthenweb/parcel-css-modules-example for more information.

## 🤔 Expected Behavior

It should resolve the sass variable `$primary-color` to css. Expected css output:

``` css
._test_dek43_5{height:100px;width:100px;background:green}
```

## 😯 Current Behavior

The variable `$primary-color` is not transpiled. Current Output:

``` css
$primary-color:green;._test_dek43_5{height:100px;width:100px;background:$primary-color}
```

There is no error from Parcel, but it returns invalid CSS, therefore the browser will not render a rectangle.

## 💁 Possible Solution

I am not 100% sure, but I guess that parcel is first running sass and afterward runs Postcss including CSS Modules. But Postcss does not transpile imported styles from sass to CSS. I assume it could work when we run sass after the Postcss transform.

I already tried to use the [`@csstools/postcss-sass`](https://www.npmjs.com/package/@csstools/postcss-sass) plugin to do so but it threw an error.

Maybe we could use the syntax parameter form the Postcss config to identify that a transform should be followed after Postcss like when the [`postcss-scss`](https://www.npmjs.com/package/postcss-scss) syntax is applied. But there might be edge cases, not sure for now...

I would love to help solving this, but I need some guidance on where to start. It would be nice to receive some tipps from the core team where to start.

## 🔦 Context

I try to migrate an existing project from Webpack to Parcel where the composes pattern is used quite a lot. The Webpack config is doing the transform by adding multiple loaders, I didn't look too much into details there but in case its helpful to solve this issue I can create an example.

## 💻 Code Sample

I created an example project to demonstrate the behavior:
https://github.com/garthenweb/parcel-css-modules-example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.14.2
| npm       | 6.4.1
| Operating System | Windows 10 using WSL/ Mac OSX

**Comment by Ty3uK** [comment]
There is bug in resolving mechanism. Compiled SASS:
```css
.test {
  height: 100px;
  width: 100px;
  background: green; }

.main {
  composes: test; }

.main {
  composes: test from './inline.scss'; }
```

So postcss inserts **composes** content from SCSS file, not from transpiled output.
