### ISSUE TITLE
Import file as raw with no processing

### ISSUE THREAD

**Issue by tiborsaas** [parcel-bundler/parcel#2527]
# 🙋 feature request

It would be sometimes helpful to be able import the raw files. For example I'd like to parse a CSS file for its contents to avoid creating a separate config object. Currently the CSS is imported and injected to the HTML.

## 🤔 Expected Behavior

Adding a `!` before the path would import it as string:

    import myRandomFile from '!./theFile.ext';
    console.log(myRandomFile) // contents of theFile.ext

## 😯 Current Behavior

It's either processed if it's a special file, like CSS or you get the path in the `dist` folder.

## 🔦 Context

```css
@font-face {
    font-family: "aileron-black";
    src: url("./woff2/aileron-black.woff2") format("woff2");
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: "aileron-blackitalic";
    src: url("./woff2/aileron-black-italic.woff2") format("woff2");
    font-weight: normal;
    font-style: normal;
}
```

I'm working on on-demand font loading for an editor and I thought that I don't want to maintain a list of fonts in a config object because I could parse if from the CSS file itself.
