### ISSUE TITLE
Unexpected CSS @import parsing

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2608]
# 🐛 bug report

## 💻 Code Sample

```css
/* style.css */
@import "./other.css"

body {
  background-color: red;
}


/* other.css */
html {
	background-color: black;
}
```

## 🤔 Expected Behavior
Output:
```css
html {
	background-color: black;
}

body {
  background-color: red;
}
```

## 😯 Current Behavior

😯😯😯

```css
@media body {
html{background-color:#000}
}
```

## 💁 Possible Solution

The import declaration is interpreted with this syntax:
`@import url list-of-media-queries;`, so
```css
@import "./other.css" body;
{
  background-color: red;
}
```
(the block at the end is ignored silently).

At first, I though about reporting this to postcss, but postcss accepts any At-Rule, so this is more related to Parcels @​import handling:
https://github.com/parcel-bundler/parcel/blob/791b4b80462fee453d82f4c711b86553daa3427e/packages/core/parcel-bundler/src/assets/CSSAsset.js#L31

## 🔦 Context

I have come across this multiple times now, just by forgetting a semicolon.

This is invalid css, an error should be thrown and not somehow transformed (the extraneous block disqualifies this a import with media query).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |master
| Node             |11
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
That's invalid css, it should be like this:

```
/* style.css */
@import "./other.css";

body {
  background-color: red;
}


/* other.css */
html {
	background-color: black;
}
```

**Comment by mischnic** [comment]
> That's invalid css, it should be like this:

That's the problem, I wrote:
> This is invalid css, an error should be thrown and not somehow transformed (the extraneous block disqualifies this a import with media query).

A missing colon throws an error:
```
🚨  .../style.css:3:7: Unknown word
  1 | @import "./other.css"
  2 |
> 3 | html {background-color blue }
    |       ^
  4 |
```
But in this case there is no error.

**Comment by DeMoorJasper** [comment]
Ow than I guess it's a postCSS issue? As that generates the errors afaik

**Comment by mischnic** [comment]
> Ow than I guess it's a postCSS issue?

Yes and no, PostCSS doesn't restrict parsing to known/correct At-Rules. For example this works just fine without any PostCSS plugins -- the emitted css simply won't work in any browser.
```css
@mixin icon youtube, red {
    background: url(youtube.png);
}
```
There could theoretically be a postcss plugin that changes the import syntax to use something like
```css
@import "something" body { color: blue; }
```
<br>
I'm not really sure anymore if/who/how this should be handled.
