### ISSUE TITLE
🐛 CSSNext (exactly 'postcss-custom-properties') doesn't work.

### ISSUE THREAD

**Issue by nakoo** [parcel-bundler/parcel#267]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

postcss.config.js
```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%']
    }
  }
};
```

CLI
```
$ parcel build app.js
```

app.js
```js
import './css/app.css'
```

### 🤔 Expected Behavior

Postcss
```css
:root {
 --font: 'Helvetica';
}

body {
 font-family: var(--font);
}
```

Exported CSS
```css
body {
 font-family: 'Helvetica';
}
```

### 😯 Current Behavior

Exported CSS
```css
/* no root pseudo-class */
body {
 font-family: var(--font);
}
```

### 💁 Possible Solution

This setting is working great when using webpack + postcss-loader.

### 🔦 Context

I tried changing the syntax of postcss setting file though there is no hope.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             |  9.3.0
| npm/Yarn         |  Yarn 1.3.2
| Operating System | Arch Linux (macOS High Sierra 10.13.2)
