### ISSUE TITLE
Wrong relative path for SASS background-image url in 1.12 on Windows

### ISSUE THREAD

**Issue by pocesar** [parcel-bundler/parcel#2758]
# 🐛 bug report

Parcel is incorrectly renaming the paths of `background: url` entries. works with 1.11, the path has no slashes

* Image path: `/images/hero-homepage-banner.jpg`

* `/src/pages/landing.tsx`
```tsx
import React from 'react'
import './landing.scss'

// ...
```

* /src/pages/landing.scss
```scss
.layout-full {
   background: url('../../images/hero-homepage-banner.jpg') no-repeat;
   background-size: cover;
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel serve ./src/index.html --https --port 443 --log-level 3 --public-url / --no-hmr
```

## 🤔 Expected Behavior

Generated css file contains a path like `url(/hero-homepage-banner.975cc93d.jpg)`

## 😯 Current Behavior

Generated CSS is:
```css
.ant-layout.layout-full {
  background: url(..\hero-homepage-banner.975cc93d.jpg) no-repeat ;
  background-size: cover;
}
```

## 🔦 Context

Impossible to use

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0
| Node             | 11.10.0
| npm/Yarn         | 6.9.0
| Operating System | Windows 10 x64
