### ISSUE TITLE
parcel wrongly transform css color 

### ISSUE THREAD

**Issue by Austaras** [parcel-bundler/parcel#2810]
# 🐛 bug report

don't know if this is parcel's bug or not, but parcel will try to tranform
``` css
input[type=range]::-ms-thumb {
  background-color: transparent;
}
```
to
```  css
input[type=range]::-ms-thumb {
  background-color: initial;
}
```
when using `parcel build` which will cause a bug in both IE and Edge
## 🎛 Configuration (.babelrc, package.json, cli command)

default configuration

## 🤔 Expected Behavior

keep transparent

## 😯 Current Behavior

transform to initial

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.1|
| Node             |11.12.0|
| npm/Yarn         |1.15.2|
| Operating System |Linux|
