### ISSUE TITLE
Parcel remove quote characters on production build css

### ISSUE THREAD

**Issue by tung-eh** [parcel-bundler/parcel#2920]
# 🐛 bug report

Parcel remove single quote on production build css

## 🎛 Configuration (.babelrc, package.json, cli command)

I add a css file like this
```html
    <link href="./index.css" rel="stylesheet">
```
In `index.css`, I define a font with some spaces in its name
```css
@font-face {
  font-family: 'Quarz 974';
  src: url('/assets/fonts/quarz974/Quarz 974 Light.woff') format('woff');
}
```

## 🤔 Expected Behavior

The css stay the same or maybe replace single quotes with double quotes

## 😯 Current Behavior

Quote characters around font name and font url have been gone
```css
@font-face{font-family:Quarz\ 974;src:url(/Quarz 974 Light.0eb3ffef.woff) format("woff")}
```

## 💁 Possible Solution

I don't know what is going on

## 🔦 Context

It just happens when run `parcel build` 
`parcel watch` and `parcel` will work normally by generating following css
```css
@font-face {
  font-family: "Quarz 974";
  src: url("/Quarz 974 Light.d8e445c3.woff") format('woff');
}
```

## 💻 Code Sample

My repo https://github.com/tung-eh/eCommerce

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.2
| Node             |8.12.0
| Yarn         |1.10.1
| Operating System |MacOS Mojave 10.14
