### ISSUE TITLE
About postcss-modules generated style

### ISSUE THREAD

**Issue by gongph** [parcel-bundler/parcel#3124]
# ❔ Question

为什么 `postcss-modules` 插件生成的样式后面总带有`_ff559` 

## 🔦 Context

也就是说，生成的 json 文件中的 class 和 dist 文件夹中的不一致

## 💻 Code Sample

`build/main.json:`

```json
{"button":"_button_1e7u6_1"}
```

`dist/main.af46ece4.css:`

```css
.__button_1e7u6_1_ff559 {
  color: pink;
  font-size: 20px;
}

/*# sourceMappingURL=/main.af46ece4.css.map */
```
可以看到 dist 下的css中多了一个 `_` 和 `_ff559`。我在使用时必须这样：

```js
import cssModule from '../../build/main.json'
export default {
  name: 'zna-button',
  render (h) {
    return h('div', {
      class: '_' + cssModule.button + '_ff559'
    }, [this.$slots.default])
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | v6.4.1/1.15.2
| Operating System | win7&64
