### ISSUE TITLE
Not working when using "postcss-import" with "postcss-next".

### ISSUE THREAD

**Issue by nakoo** [parcel-bundler/parcel#329]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

.postcssrc
```json
{
    "plugins": {
        "postcss-import": {},
        "postcss-cssnext": {}
    }
}
```

CLI
```
$ parcel build app.js
```

app.js
```js
import './app.css';
```

app.css
```css
@import "./css/root.css";
@import "./css/body.css";
```

root.css
```css
:root {
    --font: 'Helvetica';
}
```

body.css
```css
body {
    font-family: var(--font);
}
```

You can make this problem with this attachment. You can do `$ yarn run start`
[worked.zip](https://github.com/parcel-bundler/parcel/files/1570849/worked.zip)

### 🤔 Expected Behavior

Postcss
```css
:root {
 --font: 'Helvetica';
}

body {
 font-family: var(--font);
}
```

Exported CSS
```css
body {
 font-family: 'Helvetica';
}
```

### 😯 Current Behavior

Exported CSS
```css
/* no root pseudo-class */
body {
 font-family: var(--font);
}
```

### 💁 Possible Solution

This setting is working great when using webpack + postcss-loader.

### 🔦 Context

I tried changing the syntax of postcss setting file though there is no hope.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             |  9.3.0
| npm/Yarn         |  Yarn 1.3.2
| Operating System | Arch Linux (macOS High Sierra 10.13.2)
