### ISSUE TITLE
Vue styling a child component with deep selector

### ISSUE THREAD

**Issue by LucasTeirlynck** [parcel-bundler/parcel#3438]
Hey, rather simple question. Is there something similar to the vue loader's deep selector?
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

**Comment by ZiFFeL1992** [comment]
Right now I'm using this one that works:

```css
.stripe-field::v-deep {
    > div {
        width: 100%;
    }
}
```

**Comment by LucasTeirlynck** [comment]
Trying that generates me the following: 
```
.stripe-field::v-deep > div[data-v-bb9328] {
  width: 100%;
}
```

**Comment by ZiFFeL1992** [comment]
What I mean is:

```css
.class::v-deep {
    <whatever>
}
```

**Comment by LucasTeirlynck** [comment]
I've tried almost every way I could think of it but can't find a way to get it working.
Another example based on what you recommended:

```css
    .form-control::v-deep {
        .example {
            font-size: 16px;
        }
    }
```

```css
.form-control::v-deep .example[data-v-0f3827] {
  font-size: 16px;
}
```
