### ISSUE TITLE
Parcel 2: how to ignore absolute paths in css?

### ISSUE THREAD

**Issue by a-x-** [parcel-bundler/parcel#3836]
# ❔ Question

Parcel tries to bundle absolute paths inside css `url()`. It's not we need.
Am I need create custom resolver? Can you suggest how to write it?

## 🔦 Context

I have some css filed with paths to file,s that isn't available inside a project repo.

I want to skip paths like this

## 💻 Code Sample

```css
.selector {
  background: #4f5b66 url(/assets/active_admin/nested_menu_arrow.gif) no-repeat calc(100% - 7px) 50% !important;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.13.0
| npm/Yarn         | 6.12.1
| Operating System | macos mojave
