### ISSUE TITLE
tries to import datauri as a file if it is in quotes

### ISSUE THREAD

**Issue by chee** [parcel-bundler/parcel#43]
```html
<!--index.html-->
<!doctype html>
<link rel="stylesheet" href="./lol.css">
```

works!:
```css
/* lol.css */
body {
  background: url(data:image/gif;base64,something);
}
```

error:
```css
/* lol.css */
body {
  background: url("data:image/gif;base64,something");
}
```

(`🚨  /Users/chee/projects/nothing/lol.css:2:3: Cannot resolve dependency './data:image/gif;base64,something'`)
