### ISSUE TITLE
Font preload doesn't work

### ISSUE THREAD

**Issue by polRk** [parcel-bundler/parcel#5520]
# 🐛 bug report
```pug
link(rel="preload" href="fonts/Lato-Regular.woff2" as="font" crossorigin="anonymous")
link(rel="preload" href="fonts/Lato-Medium.woff2" as="font" crossorigin="anonymous")
link(rel="preload" href="fonts/Lato-Semibold.woff2" as="font" crossorigin="anonymous")
```

```css
@font-face {
    font-family: 'Lato';
    src: url('Lato-Regular.eot');
    src: local('Lato Regular'), local('Lato-Regular'),
    url('Lato-Regular.eot?#iefix') format('embedded-opentype'),
    url('Lato-Regular.woff2') format('woff2'),
    url('Lato-Regular.woff') format('woff'),
    url('Lato-Regular.ttf') format('truetype');
    font-style: normal;
    font-weight: 400;
    font-display: swap;
}

@font-face {
    font-family: 'Lato';
    src: url('Lato-Medium.eot');
    src: local('Lato Medium'), local('Lato-Bold'),
    url('Lato-Medium.eot?#iefix') format('embedded-opentype'),
    url('Lato-Medium.woff2') format('woff2'),
    url('Lato-Medium.woff') format('woff'),
    url('Lato-Medium.ttf') format('truetype');
    font-style: normal;
    font-weight: 500;
    font-display: swap;
}

@font-face {
    font-family: 'Lato';
    src: url('Lato-Semibold.eot');
    src: local('Lato Bold'), local('Lato-Bold'),
    url('Lato-Semibold.eot?#iefix') format('embedded-opentype'),
    url('Lato-Semibold.woff2') format('woff2'),
    url('Lato-Semibold.woff') format('woff'),
    url('Lato-Semibold.ttf') format('truetype');
    font-style: normal;
    font-weight: 600;
    font-display: swap;
}

```

<img width="273" alt="Screenshot 2020-12-23 at 12 27 48" src="https://user-images.githubusercontent.com/39828645/102981614-4724ea80-451a-11eb-89ce-19f35459ecf5.png">

## 🤔 Expected Behavior

Load only single copy of single font

## 😯 Current Behavior

load two copies of single font

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.463
| Node             |v10.22.1
| npm/Yarn         |6.14.6
| Operating System | Mac Os
