### ISSUE TITLE
about inline styles  and import less

### ISSUE THREAD

**Issue by de1ck** [parcel-bundler/parcel#566]
this a 🐛 bug report

### 🎛 Configuration  package.json

```js
"scripts": {
		"dev": "rm -rf .cache && rm -rf dist && parcel index.html",
		"build":
			"rm -rf .cache && rm -rf build &&  cross-env  NODE_ENV=production parcel build  index.html --no-cache  -d build/output --public-url ./",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
```

### 🤔 Expected Behavior

 I see this issue [inline style](https://github.com/parcel-bundler/parcel/issues/541)
so I use
` import '../assets/styles/login.less';`
```less
// login.less
html,
body {
    width: 100%;
    height: 100%;
    background: #f0f0f0;
    overflow: hidden;
}

.login {
    width: 100%;
    height: 100%;
    background-image: url('../images/login_bg.jpg');
    background-size: cover;
    background-position: center;
    position: relative;
    &-con {
        position: absolute;
        right: 160px;
        top: 50%;
        transform: translateY(-60%);
        width: 300px;
        &-header {
            font-size: 16px;
            font-weight: 300;
            text-align: center;
            padding: 30px 0;
        }
        .form-con {
            padding: 10px 0 0;
        }
        .login-tip {
            font-size: 10px;
            text-align: center;
            color: #c3c3c3;
        }
    }
}
```
```css
// Expected Behavior
html,
body {
  width: 100%;
  height: 100%;
  background: #f0f0f0;
  overflow: hidden;
}
.login {
  width: 100%;
  height: 100%;
  background-image: url('68e44dcd2343bc7f71b6219d49b6e588.jpg');
  background-size: cover;
  background-position: center;
  position: relative;
}
.login-con {
  position: absolute;
  right: 160px;
  top: 50%;
  transform: translateY(-60%);
  width: 300px;
}
.login-con-header {
  font-size: 16px;
  font-weight: 300;
  text-align: center;
  padding: 30px 0;
}
.login-con .form-con {
  padding: 10px 0 0;
}
.login-con .login-tip {
  font-size: 10px;
  text-align: center;
  color: #c3c3c3;
}
```

### 😯 Current Behavior

```
// parcel builder
html,
body {
  width: 100%;
  height: 100%;
  background: #f0f0f0;
  overflow: hidden;
}
._login_uad09_8 {
  width: 100%;
  height: 100%;
  background-image: url('70ce755966585831d6ab43c434f8cf52.jpg');
  -webkit-background-size: cover;
          background-size: cover;
  background-position: center;
  position: relative;
}
._login-con_uad09_16 {
  position: absolute;
  right: 160px;
  top: 50%;
  -webkit-transform: translateY(-60%);
      -ms-transform: translateY(-60%);
          transform: translateY(-60%);
  width: 300px;
}
._login-con-header_uad09_23 {
  font-size: 16px;
  font-weight: 300;
  text-align: center;
  padding: 30px 0;
}
._login-con_uad09_16 ._form-con_uad09_29 {
  padding: 10px 0 0;
}
._login-con_uad09_16 ._login-tip_uad09_32 {
  font-size: 10px;
  text-align: center;
  color: #c3c3c3;
}

```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1   
| Node             |8.4.0  
| npm/Yarn         | yarn 1.3.2 
| Operating System | win7*64
