### ISSUE TITLE
Sourcemaps are wrong with postcss-import

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5749]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.posthtmlrc:

```json
{
  "plugins": {
    "postcss-import": {}
  }
}

```

## 😯 Current Behavior

![Bildschirmfoto 2021-02-02 um 17 29 27](https://user-images.githubusercontent.com/4586894/106630547-36857c80-657c-11eb-96a3-e4715c40f9bc.png)

## 💻 Code Sample

a.css (entry):
```css
@import "./b.css";

body {
	color: red;
}
```

b.css:
```css
div {
	color: green;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 5d9143b752614c7719735b7862a0f636136e98a5
