### ISSUE TITLE
CSS font property not correctly processed

### ISSUE THREAD

**Issue by marcelkorpel** [parcel-bundler/parcel#5822]
# 🐛 bug report

An (S)CSS font property is output malformed.

## 🎛 Configuration (.babelrc, package.json, cli command)

Relevant part of `package.json`:
```js
{
  "name": "assets",
  "scripts": {
    "watch": "parcel --public-url /dist --dist-dir ./public/dist ./assets/src/index.html",
    "build": "parcel build --public-url /dist --dist-dir ./public/dist ./assets/src/index.html"
  },
  "devDependencies": {
    "@types/file-saver": "^2.0.1",
    "@vue/compiler-sfc": "^3.0.5",
    "parcel": "2.0.0-nightly.548",
    "sass": "^1.32.5",
    "typescript": "^4.1.3",
    "vue-template-compiler": "^2.6.12"
  },
  […]
}
```

## 🤔 Expected Behavior

Using the input
```css
html {
  font: 450 10pt "IBM Plex Sans";
}
```
When running `yarn watch` the output is the same as the source. When minifying this rule, the property should look like:
```css
html{font:450 10pt IBM Plex Sans}
```
## 😯 Current Behavior

When running `yarn build`, I get
```css
html{font:450 10pt,IBM Plex Sans}
/*                ^ */
```
which leads to the error 'Invalid property value', at least in Chrome and Firefox.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.548
| Node             | 15.8.0
| npm/Yarn         | 1.22.10
| Operating System | Arch Linux
