### ISSUE TITLE
CSS import order does not match the browser

### ISSUE THREAD

**Issue by evanw** [parcel-bundler/parcel#5840]
# 🐛 bug report

While investigating CSS import order esbuild.

## 🎛 Configuration (.babelrc, package.json, cli command)

Inputs:

* **entry.css**

    ```css
    @import "./file1.css";
    @import "./file2.css";
    ```

* **reset.css**

    ```css
    body {
      font-size: 10px;
      line-height: 10px;
    }
    ```

* **file1.css**

    ```css
    @import "./reset.css";
    body {
      font-size: 20px;
    }
    ```

* **file2.css**

    ```css
    @import "./reset.css";
    body {
      line-height: 20px;
    }
    ```

Command:

```js
parcel build entry.css
```

## 🤔 Expected Behavior

I believe the output should look like this:

```css
body{font-size:20px}body{font-size:10px;line-height:10px}body{line-height:20px}
```

## 😯 Current Behavior

This is what Parcel gives instead:

```css
body{font-size:10px;line-height:10px}body{font-size:20px}body{line-height:20px}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |
