### ISSUE TITLE
Getting build error while using GitHub Actions

### ISSUE THREAD

**Issue by RANISio** [parcel-bundler/parcel#5917]
# 🐛 bug report

Getting the following error while using GitHub actions: 

```
Building...
🚨 Build failed.
@parcel/core: Cannot find Parcel plugin "@parcel/transformer-html"
/home/runner/work/test-app/node_modules/@parcel/config-default/index.json:27:7
  26 |       "@parcel/transformer-posthtml",
> 27 |       "@parcel/transformer-html"
>    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/transformer-html", did you mean "@parcel/transformer-babel"?
  28 |     ],
  29 |     "*.pug": ["@parcel/transformer-pug"],
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@ build: `parcel build ./src/index.html --dist-dir dist/ --no-source-maps --no-cache`
npm ERR! Exit status 1
```

Here is my .yaml file

```
name: Staging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Staging (Master Branch)
    steps:
      - uses: actions/checkout@master
      
      - name: Intall Packages
        run: npm i

      - name: Build site
        run: npm run build
      
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'staging'
```
