### ISSUE TITLE
z-index: 10 transforms to z-index: 1 after parcel build

### ISSUE THREAD

**Issue by terenceng2010** [parcel-bundler/parcel#610]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
I don't use any configuration.

### 🤔 Expected Behavior
I have a main.css like the below:

```css
.item{
	z-index: 10;
}
```

I expect after `parcel build`, it becomes:
```css
.item{z-index:10}
```
### 😯 Current Behavior
Instead, after `parcel build`, it becomes:

```css
.item{z-index:1}
```

### 💻 Code Sample
[parcel-css-bug.zip](https://github.com/parcel-bundler/parcel/files/1650428/parcel-css-bug.zip)

run `parcel build` to reproduce it.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 6.3.1
| npm/Yarn         |  3.10.3
| Operating System | Windows 7 x64 sp1
