### ISSUE TITLE
@import *.css files not working

### ISSUE THREAD

**Issue by Ivaneyko** [parcel-bundler/parcel#6215]
# 🐛 bug report

As i understand from https://v2.parceljs.org/languages/postcss/, postcss module should work from "box" ( without installing any other dependencies ). But when i try to configure `.postcssrc` file, changes are not working

## Usage

.postcssrc
```js
{
  "modules": true,
  "plugins": {
    "postcss-import": {},
    "postcss-url": {},
    "postcss-custom-properties": {}
  }
}
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    ...
    <link rel="stylesheet" type="text/css" href="./app.css" />
  </head>
  <body>
    ...
  </body>
</html>
```
app.css
```css
@import './styles/normalize.css';

*, *::before, *::after {
  box-sizing: border-box;
}
```

## Expected Behavior

Using @import css files inside main .css file which is included into index.html
