### ISSUE TITLE
Can't include bootstrap-icons

### ISSUE THREAD

**Issue by kefyru** [parcel-bundler/parcel#6285]
I'm trying to include bootstrap & bootstrap icons using bundle.scss:
```scss
@import "~bootstrap/scss/bootstrap.scss";
@import "~bootstrap-icons/font/bootstrap-icons.css";
```
bundle.html:
```html
...
<link href="bundle.scss" rel="stylesheet"/>
...
```

bootstrap imports as expected,
but importing bootstrap-icons throws ```ENOENT: no such file or directory, open "{MyProjectFolder}/wwwsrc/fonts/bootstrap-icons.woff2"```

[node-modules]/bootstrap-icons/fonts/bootstrap-icons.css:
```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?231ce25e89ab5804f9a6c427b8d325c9") format("woff2"),
  url("./fonts/bootstrap-icons.woff?231ce25e89ab5804f9a6c427b8d325c9") format("woff");
}
```

Is there any solution?
