### ISSUE TITLE
Importing CSS/SCSS with url: prefix makes the output not being processed

### ISSUE THREAD

**Issue by sznowicki** [parcel-bundler/parcel#6456]
# 🐛 bug report

It seems like importing a css or scss file as a link makes those files not being processed by parcel and output is raw.

I stumbled upon this when creating a shadow DOM web component that needs to have the css rendered inside. Importing regular way brings them outside the `<custom-element>` which makes them not being applied to the shadow DOM nodes.

## 🎛 Configuration (.babelrc, package.json, cli command)

No config, parcel dependencies (also tested with latest nightly: 720):

```json
{
   "@parcel/transformer-sass": "2.0.0-nightly.713+003cce7b",
  "parcel": "^2.0.0-beta.3.1"
}
```

## 🤔 Expected Behavior

Output of the css/scss file should be the same.

## 😯 Current Behavior

When importing regular way, output of the scss/css file is correct, images are handled, scss is being compiled.

```jsx
import from './styles.scss
```

When importing the file as a link (with `url:` prefix) no transformations are being applied:

```jsx
import styles from 'url:./styles.scss`
```

## 🔦 Context

I need to import css within the shadow DOM root.

## 💻 Code Sample

SCSS output when importing with `url:`

```css
promo {
  background: url("./img/promo.svg");
  &__content {
    width: 100%;
  }
}
```

SCSS output when importing with no `url:` prefix.

```css
.promo {
  background: url("promo.40ebed6c.svg");
}

.promo__content {
  width: 100%;
}
/*# sourceMappingURL=index.53fb41e2.css.map */
```

Same with CSS:

CSS output when importing with `url:` prefix:
```css
.promo {
  background: url("./img/promo.svg");
}

.promo .promo__content {
  width: 100%;
}

/*# sourceMappingURL=styles.ef4c3612.css.map */
```

CSS output when importing without `url:` prefix:
```css
.promo {
  background: url("promo.40ebed6c.svg");
}

.promo .promo__content {
  width: 100%;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.3.1 |
| Node             | 16.3.0 |
| npm/Yarn         | yarn: 1.22.10 |
| Operating System | Big Sur 11.4 |
