### ISSUE TITLE
Running Parcel in GH Actions throws because of lmdb-store

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#6559]
Trying to run Parcel in a GH action resulted in throwing with
```
> parcel build ./src/index.ts && tsc

Error: The module '/home/runner/work/oz-lib/oz-lib/node_modules/lmdb-store/build/Release/lmdb-store.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/runner/work/oz-lib/oz-lib/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at load (/home/runner/work/oz-lib/oz-lib/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/home/runner/work/oz-lib/oz-lib/node_modules/lmdb-store/index.js:7:49)
    at Module._compile (/home/runner/work/oz-lib/oz-lib/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @banou26/oz-lib@0.0.1 build: `parcel build ./src/index.ts && tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @banou26/oz-lib@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-07T00_44_53_453Z-debug.log
Error: Process completed with exit code 1.
```

The GH action env is

```yaml
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
```

**Comment by devongovett** [comment]
Does it work locally for you? I'm not sure we've tested with node 16 yet.

**Comment by Banou26** [comment]
Yeah, it works locally for me while i'm running on `16.0.0`, under Windows 10

**Comment by danieltroger** [comment]
I'm ignorant but have you tried running `npm rebuild`?

**Comment by mischnic** [comment]
Is it possible that you are caching the node_module folder in GH Actions, then you upgraded your Node version and the cache still has a binary for some older Node version?

**Comment by Banou26** [comment]
I did have a caching GH action but even when removing it, it still throws. My entire action/step is
```yml
name: Create and publish a package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci

    - name: Clone MFKN/oz-web
      uses: actions/checkout@v2
      with:
        repository: MFKN/oz-web
        token: ${{ secrets.API_TOKEN }}
        path: './web'

    - run: mv ./web ../web
    - run: cd ../web
    - run: npm ci

    - run: cd ${{ env.GITHUB_WORKSPACE }}

    - run: npm run build

    - name: Upload dist folder artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: "dist/*"
```

**Edited to reflect changes done after downgrading to 14.x which is where i encounter another issue**
