### ISSUE TITLE
CSS @import ignored when providing both `screen` and `print` styles.

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#6721]
# 🐛 bug report

When providing styles for both `print` and `screen`, that `@import` a common base stylesheet, only the `screen` one has the base stylesheet inlined.

## 🎛 Configuration (.babelrc, package.json, cli command)

None

## 🤔 Expected Behavior

Both stylesheets should either inline the base stylesheet or maintain an `@import` directive to the base stylesheet.

## 😯 Current Behavior

`print` has no base styles 😢 

## 💻 Code Sample

```html
<!-- index.html -->
<!doctype html>
<link rel="stylesheet" media="print" href="./styles-print.css">
<link rel="stylesheet" media="screen" href="./styles-screen.css">
<p>Hello</p>
```

```css
/* styles-print.css */
@import "./base.css";

p {
	font-size: 80px;
}
```

```css
/* styles-screen.css */
@import "./base.css";

p {
	outline: 1px solid red;
}
```

```css
/* base.css */
p:before {
	content: "Base styles applied!";
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | rc0
| Node             | v16.4.0
| npm/Yarn         | 7.18.1
| Operating System | Mac M1
