### ISSUE TITLE
Conditional scope for importing css modules

### ISSUE THREAD

**Issue by abhinavkumar940** [parcel-bundler/parcel#7545]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
.postcssrc
{
  "plugins": {
    "tailwindcss": {},
    "autoprefixer": {}
  }
}

```

```jsx
frontend.tsx
import "./frontend.css";
import './Button';
```

```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

.slider {
foo: bar
}
```

```jsx
Button.tsx
import './Button.module.css'
```

## 🤔 Expected Behavior
It should import `Button.module.css` as a module and `frontend.css` should be imported globally

## 😯 Current Behavior

With the above configuration all css imports are scoped global. And when I add 
```
{
"modules": true,
}
```

to `.postcssrc` file none of the imports are global and even `tailwind.css` class names have `_` prefix.

## 💁 Possible Solution
If possible css-modules are scoped **only** when they have `.module` in their name otherwise they remain global.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1
| Node             | 16.13.0
| npm/Yarn         | 1.22.17
| Operating System | OSX 12.1
