### ISSUE TITLE
CSS modules + scopeHoist: composed classes removed from output CSS (regression from 2.0.0)

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#7616]
# 🐛 bug report

A CSS class that is not used in markup directly, but only in `composes: xxx`, is removed from the output styles.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration, just `yarn add parcel`

## 🤔 Expected Behavior

CSS classes used in `composes` should be kept in the output CSS

## 😯 Current Behavior

Only the derived classes remain in the output CSS

## 💁 Possible Solution

An unexpected workaround: setting `scopeHoist` to `false` keeps the classes in place

## 🔦 Context

I use some CSS classes purely to share common rules with some other classes, like ellipsis, and this approach stopped working after upgrade to the latest parcel (2.3.1) from previous (2.0.0).

## 💻 Code Sample

This is demonstrable even without JS as below. My actual JS code imports class names from the CSS modules files, but is still affected by the issue.

index.html:
```html
<!doctype html>
<html>
<head>
<style>@import url('./styles.module.css')</style>
</head>
<body></body>
</html>
```

styles.module.css:
```css
.parent {
  color: red;
}

.child {
  composes: parent;
  font-weight: bold;
}
```

output of `yarn parcel build input.html`:
```html
<!doctype html><html><head><script src="/input.eb15070c.js"></script><style>.child_9fb949{font-weight:700}</style></head><body></body></html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | v16.13.2
| Yarn         | 1.22.17
| Operating System | Ubuntu 21.10

**Comment by S-unya** [comment]
I also have this issue. As far as I can tell there are 3 fundamental problems with the way parcel handles css modules (but my use case is a little complicated because I use css modules with scss):

1. At some point in the process the `composes` rule is stripped out, which I imagine is correct, but a class name is not always added to the component to represent the composed rules (this appears to be the case for both CSS modules and SCSS with CSS modules) 
2. If one uses `composes` for an external css module file (rather than a local class name as in the example above), then the file is added as an `@import` to the output css. This can be really problematic if one is using css modules in scss because it results in broken css. 
3. If one has multiple composes of the same file across multiple files, this will result in multiple `@import` statements at the top of the compiled css file

Here is an example of the worst case scenario:

.postcssrc
```
{
    "plugins": {
        "postcss-modules": {
            "generateScopedName": "_[name]__[local]"
        }
    }
}
```

a.module.scss
```scss
.component {
    --comp-context-menu-width: 240px;
    composes: full from "../../styles/layout.module.scss";
    position: relative;
}
```

layout.module.scss
```scss
.full {
    grid-column: full !important;
}
```

compiled.css
```css
@import "../../styles/layout.module.scss";

._a-module__component {
  --comp-context-menu-width: 240px;
  position: relative;
}
```
