### ISSUE TITLE
@imports inside CSS modules are ordered differently than non-modules

### ISSUE THREAD

**Issue by shepmaster** [parcel-bundler/parcel#7950]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**

```json
{
  "name": "repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.4.1"
  },
  "dependencies": {
    "normalize.css": "^8.0.1"
  }
}
```

## 🤔 Expected Behavior

I expect that normalize.css will occur in the output CSS before the custom CSS, as the `@import` comes first. This should work if I'm using CSS modules or not.

## 😯 Current Behavior

**styles.css** (expected)

```css
/* contents of normalize.css */

h1 {
  color: #ff69b4;
  font-family: cursive;
}
```

**styles.module.css** (unexpected)

```css
h1 {
  color: #ff69b4;
  font-family: cursive;
}

/* contents of normalize.css */
```

## 🔦 Context

When the CSS is in an unexpected order, I have to resort to using `!important` to override things that normally I wouldn't need to.

## 💻 Code Sample

**src/index.html**

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My First Parcel App</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

**src/styles.css** and **src/styles.module.css**

```css
@import "npm:normalize.css";

h1 {
  color: hotpink;
  font-family: cursive;
}
```

1. Run `yarn parcel src/index.html --no-cache` and view the generated stylesheet.
1. Change `<link rel="stylesheet" href="styles.css" />` to `<link rel="stylesheet" href="styles.module.css" />` 
1. Run `yarn parcel src/index.html --no-cache` and view the generated stylesheet.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 17.9.0
|Yarn         | 1.22.18
| Operating System | macOS 12.3.1

# 🔍 Related?

- #5469
- #5840
- #7844
