### ISSUE TITLE
CSS @import wrong order

### ISSUE THREAD

**Issue by sineway** [parcel-bundler/parcel#8038]
Let's say you have 2 files:

```css
/* red.css */
body { color: red }
```

```css
/* green.css */
body { color: green }
```
Then you import them:
```css
@import "red.css";
@import "green.css";
```

Then comment first import and save file:
```css
/* @import "red.css"; */
@import "green.css";
```
Then uncomment first import and save file again.
Order becomes wrong:
```css
/* green.css */
body { color: green }
/* red.css */
body { color: red }
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 17.9.0
| npm         | 8.5.5
| Operating System | Linux
