### ISSUE TITLE
Allow just hash url's in CSS

### ISSUE THREAD

**Issue by GrimLink** [parcel-bundler/parcel#8125]
# 🐛 bug report

With Parcel v2 you can not use a url with just hash in it `mask-image: url("#")`.

Why would you want this you may ask.
Wel this is a common use case to use with the css mask property,
if you want to easily swap values with CSS variables.

Let say you have checkbox using a dataUri image for the checked state, 
but for the unchecked state you want the value to be empty.
The `none` value with not work since the background color is set and wil paint the box,
but if a url is set with a hash this will work, and there is no color set on the element.

## 🎛 Configuration (.babelrc, package.json, cli command)

_Nothing special to mention basic ParcelJS setup_

## 🤔 Expected Behavior

No errors.

## 😯 Current Behavior

Errors on the url path.

## 💁 Possible Solution

Allow url's in CSS with just a hash

## 🔦 Context

_See bug report for more context_

## 💻 Code Sample

```css
[type="checkbox"] {
    --control-icon: url("#");
    --control-checked-icon: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='3'%3E%3Cpath d='M20 6L9 17l-5-5'/%3E%3C/svg%3E");
}

[type="checkbox"]::before {
    background-color: currentColor;
    mask-image: var(--control-icon);
}

[type="checkbox"]:checked::before {
    mask-image: var(--control-checked-icon);
}
```

_There is of course more CSS needed in this sample, this is just focusing on the thing that is needed and does not work in Parcel_

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.5.0 |
| Node             | v16.14.0
| npm/Yarn         | v8.3.1
| Operating System | MacOS 12.3
