### ISSUE TITLE
No codeframe when importing missing CSS modules variable

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8142]
# 🐛 bug report

## 🤔 Expected Behavior

The error when importing missing CSS modules variable should say where the variable is imported (just like with JS imports).

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/core: b.module.css does not export '--colors'

```

## 💁 Possible Solution

There should be an actual loc here instead of null

https://github.com/parcel-bundler/parcel/blob/f2d0a3a27d6e493b23ddc2edbc8a4c0053ff34ab/packages/transformers/css/src/CSSTransformer.js#L239

## 💻 Code Sample

a.module.css
```css
.foo {
  color: var(--colors from "./b.module.css");
}
```

b.module.css
```css
:root {
  --color: red;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | f2d0a3a27d6e493b23ddc2edbc8a4c0053ff34ab
