### ISSUE TITLE
Parcel autoprefixer bug.

### ISSUE THREAD

**Issue by DeveloperAspire** [parcel-bundler/parcel#8295]
# 🐛 bug report
I used parcel to bundle my scss/css a while ago, I wrote a background gradient without auto prefixing and Parcel was able to add auto prefixing so it works out of the box, but after some days I went back to the app and I found out Parcel couldn't add the auto prefixer anymore and doesn't even bundle it well, so the background gradient stopped working, I fired an app I created a while ago totally different from the app I am currently working on it and also has the same configuration, it worked fine there but when I start a fresh project with parcel with the exact same configuration, it doesn't work, I have tried all the best I can and it still doesn't work.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "beta",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "source": "index.html",
  "scripts": {
    "dev": "parcel --port 3000"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "2.6.2",
    "parcel": "^2.6.2"
  }
}

```

## 🤔 Expected Behavior
Parcel would previously auto prefix by itself but it doesn't do that anymore and doesn't bundle the application well.

## 😯 Current Behavior

It should add the auto prefixer by itself as it does before.

![Screenshot from 2022-07-10 14-03-42](https://user-images.githubusercontent.com/57295537/178146097-9d3a164f-1aa8-406b-a76a-d2b95e985630.png)

As you will see from the screenshot, as it cannot prefix it properly, it adds a "text" behind the color.

I also checked the bundled css and I found this

```css

.container .heading {
  font-size: to-rem(90px);
  margin: to-rem(20px) 0;
  color: #0000;
  background: linear-gradient(90deg, #020024 0%, #302b2f 0%, #685e3d 0%, #e95ce3 0%, #325ddc 38%, #00fff8 75%) text;
}
```
It adds a weird "text" instead of just bundling it to the code below

```css
.container .heading {
  color: #0000;
  background: linear-gradient(90deg, #020024 0%, #302b2f 0%, #685e3d 0%, #e95ce3 0%, #325ddc 38%, #00fff8 75%);
  -webkit-background-clip: text;
  background-clip: text;
  margin: 1.25rem 0;
  font-size: 5.625rem;
}
```
The above code is the expected behavior

## 🔦 Context

I am trying to create a gradient text using css, using the css properties of background and background-clip: text, formally parcel would bundle and add the autoprefixer but now it doesn't.

## 💻 Code Sample

```css

body {
  background-color: black;
}

.container {
  background-color: inherit;
  color: white;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
}

.container .heading {
  font-size: to-rem(90px);

  margin: to-rem(20px) 0;
  background: linear-gradient(
    90deg,
    #020024 0%,
    #302b2f 0%,
    #685e3d 0%,
    #e95ce3 0%,
    #325ddc 38%,
    #00fff8 75%
  );
  color: transparent;
  background-clip: text;
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | v16.14.0
| Yarn         | 1.22.18
| Operating System | Ubuntu
