### ISSUE TITLE
Nesting not works properly when use dashes to get compound class names

### ISSUE THREAD

**Issue by barcia** [parcel-bundler/parcel#8403]
# 🐛 bug report

The CSS nesting not works properly when use dashes to get compound class names

## 🎛 Configuration
package.json:
```js
  "@parcel/transformer-css": {
    "drafts": {
      "nesting": true
    }
  },
```

## 🤔 Expected Behavior

Input:
```css
.Home {
  &-images {
    display: flex;
  }
}
````

Output:
```css
.Home-images {
  display: flex;
}
```

## 😯 Current Behavior

Input:
```css
.Home {
  &-images {
    display: flex;
  }
}
````

Output:
```css
-images.Home {
  display: flex;
}
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 16.14.2
| npm/Yarn         | 8.5.0
| Operating System | MacOS 12.5
