### ISSUE TITLE
Support for css-modules `:local`/`:global`?

### ISSUE THREAD

**Issue by kubijo** [parcel-bundler/parcel#8463]
# 💬 RFC

Is [the `exceptions` section of `css-modules` spec](https://github.com/css-modules/css-modules#exceptions) supposed to be implemented in the built-in implementation?

I am getting many instances of the following error:

> @parcel/transformer-css: Unsupported pseudo class or element: global

## 🔦 Context

I'm trying to migrate from Webpack to Parcel, but the `css-modules` implementation seems to differ.
Example code would be:
```scss
.fileInput :global {
    .bx--file,
    .bx--file-browse-btn,
    .bx--file__selected-file {
        width: 100% !important;
        max-width: 100% !important;
    }
}
```
