### ISSUE TITLE
Aspect-ratio media query decimal transformation

### ISSUE THREAD

**Issue by proto-n** [parcel-bundler/parcel#8735]
# 🐛 bug report

Parcel seems to transform the aspect-ratio media query into decimal values.

### relevant package.json
```js
{
  // ...
  "devDependencies": {
    // ...
    "@parcel/packager-raw-url": "^2.5.0",
    "@parcel/transformer-sass": "^2.5.0",
    "@parcel/transformer-webmanifest": "^2.5.0",
    "parcel": "^2.8.2",
    "parcel-reporter-static-files-copy": "^1.3.4",
    "process": "^0.11.10",
    "punycode": "^1.4.1",
  },
}
```
### .parcelrc
```js
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
}

```

## 🤔 Expected Behavior
In a CSS file I have:
```css
@media (max-aspect-ratio: 1/1) {
  .mid-container{
    visibility: hidden;
  }
}
```
I expect to have the same in the output css.

## 😯 Current Behavior

It gets transformed to
```css
@media (max-aspect-ratio: 1) {
  .mid-container {
    visibility: hidden;
  }
}
```
and thus doesn't work.

## 💁 Possible Solution

Could not find any workarounds.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |^2.8.2
| Node             |v16.13.0
| npm/Yarn         | npm 8.3.0
| Operating System | Linux Mint 20.3 Una
