### ISSUE TITLE
 🐛 The bundled css is in the wrong order.

### ISSUE THREAD

**Issue by cjnucette** [parcel-bundler/parcel#874]
###  🐛 
I have three css files imported in the following order: main.js imports main.css and App.js, App.js imports App.css and Card.js, Card.js imports Card.css. The resulting  css has the content of this files in this order: Card.css, App.css, main.css, and obviously this causes all kind of problems.

### 🎛 Configuration (.babelrc, package.json, cli command)
```js
{
  "presets": { "env": "hyperapp" }
}
```

### 🤔 Expected Behavior

Should bundle the file in the given order.

### 🔦 Context

In this case in particular the @import rule is misplaced.

### 💻 Code Sample

```css
.danger {
  background: rgba(139, 0, 0, 0.3);
  color: darkred;
  border: 2px solid rgba(139, 0, 0, 0.3);
}@import url('https://fonts.googleapis.com/css?family=Roboto|Montserrat');

:root {
  --color-pri: #444;
  --bg-accent: #007bff;
  --mg-bt: 1rem;
  --bd-rd: 5px;
  --content-width: 80%;
}

```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 9.5.0
| npm/Yarn         | 5.6.0
| Operating System | Ubuntu 17.10
