### ISSUE TITLE
Bus error with build

### ISSUE THREAD

**Issue by muhammadnasr** [parcel-bundler/parcel#8759]
# 🐛 bug report

Bus Error: 10 when using build
## 🎛 Configuration (.babelrc, package.json, cli command)

I am using parcel v2.8.2

## 🤔 Expected Behavior
No errors 
## 😯 Current Behavior

I get this error in console:
/var/folders/fn/g76_f0gs7_b5_3nb24hdksmw0000gn/T/npx6733362834.sh: line 2: 80330 Bus error: 10      

When running parcel build in my project which is quite big,

## 💁 Possible Solution

Workarounds:
Use Parcel serve which has no problems
Also parcel build with --no-optimize has no problems

## 🔦 Context

Building my frontend for production (I am a big fan of parcel and using it to replace webpack )

## 💻 Code Sample

Private

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.2
| Node             | 14.17.6
| npm/Yarn         | rpm 8.13.2
| Operating System | Mac OS ventura

**Comment by devongovett** [comment]
We will need a reproduction so we can debug

**Comment by muhammadnasr** [comment]
@devongovett 
Thank you for prompt reply.
Unfortunately my project is proprietary and cannot be shared.
How can I send you logs, where can I find them?

**Comment by mischnic** [comment]
Just logs won't really help

**Comment by amurashincertinia** [comment]
Hello there, I also came across this error and managed to extract a small repro from our project.


```scss
// test.scss

$max-width: 2rem;
$row-gap: 1rem;
$padding: 0; // fails without units, builds fine with units

.test {
  padding-inline-start: max(
    (25% - #{$max-width + $row-gap}) - #{$padding * 2},
    #{$padding}
  );
}
```

Changing the `$padding` value from unitless `0` to `0rem` or `0px` or any other unit makes the build happy.
