### ISSUE TITLE
CSS autoprefixes are duplicated

### ISSUE THREAD

**Issue by remino** [parcel-bundler/parcel#8770]
# 🐛 bug report

When building a CSS file, Parcel adds some compatibility prefixes, but sometimes duplicates them.

Tried both from a Sass file and a plain CSS file.

### package.json

```js
{
  "name": "parceltrial2",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Rem",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.8.2"
  }
}
```

### main.sass

```
body
	backdrop-filter: blur(10px)
```

#### Command to build and output

```sh
parcel build main.sass && cat build/main.css
```

### main.css

```
body {
	backdrop-filter: blur(20px);
}
```

#### Command to build and output

```sh
parcel build main.css && cat build/main.css
```

## 🤔 Expected Behavior

The output CSS should only have one `-webkit-backdrop-filter`:

```css
body{-webkit-backdrop-filter:blur(10px);backdrop-filter:blur(10px)}
/*# sourceMappingURL=main.css.map */
```

## 😯 Current Behavior

Each of the two commands stated above produced the same output:

```css
body{-webkit-backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);backdrop-filter:blur(10px)}
/*# sourceMappingURL=main.css.map */
```

## 🔦 Context

Trying to minimize file sizes and redundancy.

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 18.11.0
| npm/Yarn         | 8.19.2
| Operating System | macOS Venture 13.0.1
