### ISSUE TITLE
Parcel doesnt produce output files in Docker

### ISSUE THREAD

**Issue by 4tl4sCode** [parcel-bundler/parcel#8771]
I have a very weird behaviour with Parcel. Basically i am building my React Project in a Docker Container, which uses the node alpine image. When building the container it does a npm install and a npm run build (which executes parcel build). When just running `sudo docker-compose up` it does produce output that it is "building", but the dist folder is no where to be seen (already did a find in the complete file system and its nowhere...). The stupid thing is, when i go into the container via shell and execute `npm run build` it gives me the same stdout, but actually also creates the files from the build.
Sadly Parcel also does not give any error message i could google for.

Although one thing which could be a possible reason (i dont know) is that i saw that all files are created by the use node and my manual created files so dist/* are owned by me (root)

This is my package.json:
```json
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.27.2",
    "bootstrap": "^5.2.0",
    "jquery": "^3.6.1",
    "lodash.debounce": "^4.0.8",
    "markdown-to-jsx": "^7.1.7",
    "moment": "^2.29.4",
    "react": "^18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "react-markdown": "^8.0.3",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^2.1.3",
    "react-svg": "^15.1.18",
    "react-syntax-highlighter": "^15.5.0",
    "rsuite": "^5.19.0"
  },
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --no-cache --no-source-maps --log-level verbose"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": [
    "last 1 chrome versions"
  ],
  "devDependencies": {
    "buffer": "^5.7.1",
    "parcel": "^2.0.0"
  }
}
```
Docker-Compose:
```yaml
version: '3.8'
services:
  react:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    command: ["bash", "./docker/react_entrypoint.sh", "./app", "production"]
    #command: ["ls", "-al", "app/"]
    volumes:
     - ./frontend:/app/frontend
    #env_file:
    #  - .env

  django:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    command: ["bash", "./docker/django_entrypoint.sh", "./api/", "production"]
    expose:
      - "8000"
    volumes:
      - ./backend/api:/app/api
    env_file:
      - .env
    environment:
      - MODE=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./ssl-certs/atlassec.crt:/etc/ssl/certs/atlassec.crt
      - ./ssl-certs/atlassec.key:/etc/ssl/private/atlassec.key
      - ./nginx/templates:/etc/nginx/templates
      #- ./frontend/app/dist:/var/www/dist
    env_file:
      - .env
    depends_on:
      - react
      - django
```

This is the docker file:
```docker
# Use the official Node.js image as the base image
FROM node:alpine

RUN apk add --no-cache bash

# Create a directory for the React app
WORKDIR /app/frontend
COPY . .

WORKDIR /app/frontend/app

RUN find / -name dist 2>/dev/null

RUN npm install
RUN npm run build

WORKDIR /app/frontend
```
