### ISSUE TITLE
Improving Caching on GitHub Actions for Unchanged Assets between Commits

### ISSUE THREAD

**Issue by navidemad** [parcel-bundler/parcel#8781]
Thank you for your open-source build tool. It is very fast and efficient.

**I am currently trying to optimize my GitHub action by implementing caching.**

## 🐞 Problem

Even though my stylesheets assets remain unchanged between two commits, the building step takes around 41210ms for parcel to build. However, when I run the command multiple times `yarn build:css` on my local computer with stylesheets assets unchanged, it only takes 415ms each time.

Source: https://parceljs.org/features/development/#caching

> Parcel caches everything it builds to disk. If you restart the dev server, Parcel will only rebuild files that have changed since the last time it ran. Parcel automatically tracks all of the files, configuration, plugins, and dev dependencies that are involved in your build, and granularly invalidates the cache when something changes. For example, if you change a configuration file, all of the source files that rely on that configuration will be rebuilt. By default, the cache is stored in the .parcel-cache folder inside your project.

This issue seems to be similar if it is helpful for you https://github.com/parcel-bundler/parcel/discussions/5068 https://github.com/parcel-bundler/parcel/issues/5927#issuecomment-1250395079

Please let me know if you require any additional information.

## 🔦 Context

Rails on Rails 7.0.4.1 with cssbundling-rails and @parcel/core 2.8.3

```js
import { Parcel } from "@parcel/core";
import glob from "glob";
import path from "path";

const __dirname = path.resolve();

let bundler = new Parcel({
  entries: glob.sync(path.resolve(__dirname, `app/assets/stylesheets/*.scss`)),
  defaultConfig: "@parcel/config-default",
  defaultTargetOptions: {
    distDir: path.resolve(__dirname, "app/assets/builds"),
    sourceMap: true,
  },
  mode: "production",
  minify: true,
  env: {
    NODE_ENV: "production",
  },
});

try {
    let { buildTime } = await bundler.run();
    console.log(`compilation css: ${buildTime}ms`);
} catch (err) {
    console.error(`compilation css:`, err.diagnostics);
}
```

```yml
- name: 📂 Cache /.parcel-cache
  uses: actions/cache@v3
  with:
    path: |
      .parcel-cache
    key: ${{ runner.os }}-parcel-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ github.event.pull_request.head.sha || github.sha }}
    restore-keys: |
      ${{ runner.os }}-parcel-cache-${{ github.event.pull_request.head.ref || github.ref }}-
      ${{ runner.os }}-parcel-cache-

- name: 📂 Cache /app/assets/builds
  uses: actions/cache@v3
  with:
    path: |
      app/assets/builds
    key: ${{ runner.os }}-app-assets-builds-${{ github.event.pull_request.head.ref || github.ref }}-${{ github.event.pull_request.head.sha || github.sha }}
    restore-keys: |
      ${{ runner.os }}-app-assets-builds-${{ github.event.pull_request.head.ref || github.ref }}-
      ${{ runner.os }}-app-assets-builds-

- name: Precompile assets with parcel
  shell: bash
  run: bin/yarn build:css
```

Which outputs on the CI:

```yml
  bin/yarn build:css
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    RAILS_ENV: test
    NODE_ENV: test
    RAKE_ENV: test
    CI: true  
compilation css
compilation css: 41210ms
```

The cache is correctly created and restore
```
Post 📂 Cache /app/assets/builds
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/foo-bar/foo-bar --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~10 MB (9976485 B)
Cache saved successfully
Cache saved with key: Linux-app-assets-builds-enhancements-system-tests-assets-40cf64044436c0198afd4a4c121a17e0d514fb55

Post 📂 Cache /.parcel-cache
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/foo-bar/foo-bar --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~28 MB (29308801 B)
Cache saved successfully
Cache saved with key: Linux-parcel-cache-enhancements-system-tests-assets-40cf64044436c0198afd4a4c121a17e0d514fb55
```

Let me know if you need more informations.
