### ISSUE TITLE
HMR not connecting with Docker setup even with ports specified

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#8966]
# 🐛 bug report

I have created a simple test repo where HMR fails when running it via Docker (even though the port is specified and exposed).

Using this repo with either branch:
* node:18-bullseye debian base image branch: https://github.com/mrcoles/simple-parcel-site/tree/feature/debian
* node:14.17-alpine base image branch: https://github.com/mrcoles/simple-parcel-site/tree/main

Follow these steps:

1. Clone [repo](https://github.com/mrcoles/simple-parcel-site/tree/feature/debian)
2. Optionally try the feature/debian branch instead of alpine linux, which should work on Apple M1 processors (`git checkout feature/debian`)
3. Run the server, `docker compose up`
4. Visit the URL: http://localhost:1234/
5. From the dev console you’ll see:

    > WebSocket connection to 'ws://localhost:1239/' failed: 
    > undefined
    >  [parcel] 🚨 Connection to the HMR server was lost

6. In contrast just run plain old `yarn install && yarn start` without Docker and edits to `index.tsx` show up automatically in the browser

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```js
{
  "name": "simple-parcel-site",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "start": "parcel --hmr-port 1239 --hmr-host localhost src/index.html"
  },
  "devDependencies": {
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "parcel": "2.8.3",
    "process": "^0.11.10"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}

```

docker-compose.yml:

```yml
version: "3"

volumes:
  local_client_cache: {}
  local_client_dist: {}

services:
  client:
    build:
      context: .
      dockerfile: ./compose/client/Dockerfile
    image: simpleparcelsite_website_local_client
    volumes:
      - ./:/app
      - /app/node_modules
      - local_client_cache:/app/.parcel-cache
      - local_client_dist:/app/dist
    ports:
      - "1234:1234"
      - "1239:1239"
    command: start
```

Dockerfile

```
FROM node:18-bullseye

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

ENTRYPOINT ["yarn"]
CMD ["start"]
```

## 🤔 Expected Behavior

I would expect the Websocket connection for HMR to work and edits to files to auto-reload the page.

## 😯 Current Behavior

The HRM error from above happens in the dev console. There’s nothing about it in my dev terminal:

> Attaching to simple-parcel-site-client-1
> simple-parcel-site-client-1  | yarn run v1.22.19
> simple-parcel-site-client-1  | $ parcel --hmr-port 1239 --hmr-host localhost src/index.html
> simple-parcel-site-client-1  | Server running at http://localhost:1234
> simple-parcel-site-client-1  | Building...
> simple-parcel-site-client-1  |
> simple-parcel-site-client-1  | console: Browserslist: caniuse-lite is outdated. Please run:
> simple-parcel-site-client-1  |   npx update-browserslist-db@latest
> simple-parcel-site-client-1  |   Why you should do it regularly:
> simple-parcel-site-client-1  | https://github.com/browserslist/update-db#readme
> simple-parcel-site-client-1  | Bundling...
> simple-parcel-site-client-1  | Packaging & Optimizing...
> simple-parcel-site-client-1  | ✨ Built in 1.05s

## 💁 Possible Solution

Not sure.

## 🔦 Context

HMR not working in my Docker setup hurts productivity/moral of my team.

## 💻 Code Sample

Repo listed above: https://github.com/mrcoles/simple-parcel-site/tree/feature/debian

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 18.16.0 |
| Yarn         | 1.22.19 |
| MacOS | 12.6.3 |
| Docker Compose | v2.6.1 |
| Debian | bullseye |
