### ISSUE TITLE
Unable to use old media query format

### ISSUE THREAD

**Issue by lexuzieel** [parcel-bundler/parcel#9139]
# 🐛 bug report

My media queries get rewritten in a newer format that doesn't work on old Safari browser.

My source code:

```css
@media (max-width: 991px) {
  .hidden-mobile {
    display: none;
  }
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

As per the docs I added `browserslist` to my package.json:

```json
{
  "browserslist": "> 0.5%, last 3 versions, not dead"
}
```

## 🤔 Expected Behavior

Media query is left intact.

## 😯 Current Behavior

Media query gets rewritten as such:

```css
@media (width <= 991px) {
  .hidden-mobile {
    display: none;
  }
}
```

## 💁 Possible Solution

It looks like browserlist option doesn't have any effect.

## 🔦 Context

I've also tried setting browser list to something like "last 300 versions", "dead", "Firefox 48". But there was no effect.

----

Actually I made it working after some time with the following config:

.parcelrc:

```json
"transformers": {
    "*.css": [
      "@parcel/transformer-css"
    ]
  }
```

package.json:

```json
"browserslist": "> 0.5%, last 2 versions, not dead, Safari 14"
```

Still, it only works for `parcel build`, not just `parcel`.

So in the end it looks like `browserlist` is working, however `@parcel/transformer-postcss` and `@parcel/transformer-css` plugins are conflicting somehow?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 18.12.1
| npm/Yarn         | 8.19.2
| Operating System | Windows 11
