### ISSUE TITLE
Duplicate CSS properties are output in the wrong order

### ISSUE THREAD

**Issue by evanminto** [parcel-bundler/parcel#9141]
# 🐛 bug report

Sometimes I need to include the same CSS property twice with two different values to create a fallback in older browsers. For example (not exactly a practical example but for demonstration purposes):

```css
.my-component {
  width: 50%;
  width: var(--my-var);
}
```

When the code is built in either dev or prod, it moves the `width: 50%` to the bottom, changing the intent of the source code.

## 🎛 Configuration

package.json:

```json
{
  "name": "parcel-css-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.9.3"
  }
}
```

## 🤔 Expected Behavior

It should output:

```css
.my-component {
  width: 50%;
  width: var(--my-var);
}
```

## 😯 Current Behavior

It outputs:

```css
.my-component {
  width: var(--my-var);
  width: 50%;
}
```

## 💁 Possible Solution

At the very least there should be an option to turn this behavior off and allow the order of duplicate properties to be observed. If there is an option I couldn’t find it.

## 🔦 Context

The order of duplicate properties is important for fallbacks for cross-browser support and the transformer shouldn’t modify this.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 18.12.1
| Yarn         | 1.22.19
| Operating System | MacOS Ventura 13.4
