### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by malonehedges** [parcel-bundler/parcel#94]
Hi,

I have three files which I will put below. When using the `parcel watch src/index.html` or `parcel src/index.html` commands, everything is fine and works great. However, using `parcel build src/index.html` fails with the following error:

```
❯ parcel build src/index.html
🚨  /Users/me/projectpathhere/src/index.js: Cannot read property 'start' of undefined
    at module.exports (/Users/me/.config/yarn/global/node_modules/babel-to-estree/babylon-to-espree/attachComments.js:56:41)
    at module.exports (/Users/me/.config/yarn/global/node_modules/babel-to-estree/babylon-to-espree/index.js:35:3)
    at exports.toEstree (/Users/me/.config/yarn/global/node_modules/babel-to-estree/index.js:9:3)
    at module.exports (/Users/me/.config/yarn/global/node_modules/parcel-bundler/src/transforms/uglify.js:10:39)
    at <anonymous>
```

Also would like to point out that doing `parcel build src/index.js` fails, but `parcel build src/style.css` works.

And now the files:

### `src/index.html`

```html
<!doctype html>
<html>
<head>
  <title>w o w</title>
</head>
<body>
  <h1>WOW</h1>
  <script src='./index.js'></script>
</body>
</html>
```

### `src/index.js`

```js
import randomColor from 'randomcolor'
import './style.css'

setInterval(() => {
  document.body.style.backgroundColor = randomColor({
    luminosity: 'bright',
  })
}, 500)
```

### `src/style.css`

```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  transition: background-color 0.5s ease-in;
}

h1 {
  text-align: center;
  color: #ffffff;
  font-weight: 800;
  font-size: 5em;
  line-height: 5em;
}
```
